[project]
name = "polars-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "polars[all]>=1.36.1",
]
